---

# Main IP address
- name: Build reverse IP address using shell
  shell: >-
    dig -x {{ external_ip }}
    @{{ bind.forward[0] }}
    | awk 'f{print;f=0} /^;; QUESTION SECTION:/{f=1}'
    | sed -E 's/(^;|.IN.*)//g'
  register: reverse_main_ip

- name: Build the reverse IP address (works for IPv4 or IPv6)
  tags: facts
  set_fact:
    reverse_ip: "{{ reverse_main_ip.stdout }}"

- name: Set external IP address type (A or AAAA)
  register: main_ip_type
  shell:
    echo {{ external_ip }}
    | grep -E '^[0-9\.]+$' 2>&1 >/dev/null
    && echo A || echo AAAA

- name: Set external IP address type (A or AAAA)
  set_fact:
    external_ip_type: '{{ (main_ip_type.stdout) }}'

# Backup IP address
- name: Build reverse IP address using shell
  when: network.backup_ip is defined
  shell: >-
    dig -x {{ network.backup_ip }}
    @{{ bind.forward[0] }}
    | awk 'f{print;f=0} /^;; QUESTION SECTION:/{f=1}'
    | sed -E 's/(^;|.IN.*)//g'
  register: reverse_backup_ip

- name: Build the reverse IP address (works for IPv4 or IPv6)
  when: network.backup_ip is defined
  tags: facts
  set_fact:
    reverse_backup_ip: "{{ reverse_backup_ip.stdout }}"

- name: Set external IP address type (A or AAAA)
  when: network.backup_ip is defined
  register: backup_ip_type
  shell:
    echo {{ network.backup_ip }}
    | grep -E '^[0-9\.]+$' 2>&1 >/dev/null
    && echo A || echo AAAA

- name: Set external IP address type (A or AAAA)
  when: network.backup_ip is defined
  set_fact:
    backup_ip_type: '{{ (backup_ip_type.stdout) }}'
