---

- name: Create a directory for DNSSEC keys backup if it does not exists
  delegate_to: localhost
  become: no
  file:
    path: '{{ playbook_dir }}/{{ domain }}/dnssec-keys/'
    state: directory

- name: bind package present
  apt:
    name:
      - bind9
      - dnsutils
    state: present

# no longer relevant on buster    
# When IPv6 is used, bind9 should be taken from backports
# TODO: Configure this automatically
    #default_release: stretch-backports

- name: DNS master at {{ ansible_default_ipv4.address }}
  debug: 

- name: Stop the DNS server before creating the configuration
  service: name=bind9 state=stopped

# If we move to a stealth primary, do not list it as an NS in the zone
# file.  Those NS records must match what the registrar points to.  If
# we use TSIG for dynamic, the zone file should be in /var/lib/bind
# instead.

# We just configure a forward zone.  Linode manages the reverse DNS at
# their end.

# This uses sec since 1970 as the serial.  The serial is an unsigned
# 32bit value so we should be good until 2099.
- name: zone files present
  vars:
    serial: "{{ lookup('pipe', 'date +%s') }}"
    ipv4_address: '{{ ansible_default_ipv4.address }}'
  template:
    src: zonefile
    dest: /etc/bind/db.{{ zone.name }}
    mode: 0640
  with_items: "{{ dns_zones }}"
  loop_control:
    loop_var: zone

- name: bind configuration present
  template:
    src: "{{ item }}"
    dest: /etc/bind/{{ item }}
    mode: 0644
  with_items:
    - named.conf.local
    - named.conf.options
    
