---
# Initial config of a server to lock down ssh.

- name: First setup of new server
  hosts: all
  gather_facts: no
  remote_user: root
  port: 22
  tasks:
    # do this first to minimize the number of log entries in
    # a different time zone
    - name: timezone set to {{ timezone }}
      timezone:
        name: "{{ timezone }}"
        
    - name: update the package list
      apt:
        update_cache: yes
        cache_valid_time: "{{ pkg_cache_life }}"

    # upgrade yes/safe will not remove or install new pkgs, just
    # get the latest versions of everything.
    - name: upgrade a server with apt
      apt: upgrade=dist

    - name: common groups present
      group: name="{{ item }}" state=present
      with_items:
        - users
        - wheel

    - name: wheel group allowed to sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) ALL'
        validate: 'visudo -cf %s'

    - name: deploy account with wheel group present
      user:
        name: "{{ deploy_acct.name }}"
        group: "{{ deploy_acct.group }}"
        groups: wheel
        append: yes
        state: present
        password: "{{ deploy_acct.passwd }}"
      
    - name: accounts have authorized keys
      authorized_key: user="{{ item.name }}" key="{{ item.sshkey }}"
      with_items:
        - "{{ root_acct }}"
        - "{{ deploy_acct }}"
      
    - name: ssh password authentication off
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: 'PasswordAuthentication no'
        insertafter: EOF
        state: present

    - name: modern host key present
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: 'HostKey /etc/ssh/ssh_host_ed25519_key'
        insertafter: EOF
        state: present

    - name: missing host keys generated
      command: ssh-keygen -A

    - name: restart ssh
      service: name=ssh state=restarted




    
    
