---
# Initial config of a server to lock down ssh.
# LIMIT THE PLAY to the just the machine that you want set up.
# ansible-playbook site.yml --limit foobar --tags first

- name: first setup of new server
  hosts: all
  gather_facts: no
  remote_user: "{{ first_acct }}"
  port: 22
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#    ansible_ssh_private_key_file: "{{ root_acct.sshkeypath }}"
  roles:
    - first
