---
# Initial config of a server to lock down ssh.

# Initial config of a server to lock down ssh.
# LIMIT THE PLAY to the just the machine that you want set up.
# ansible-playbook site.yml --limit foobar --tags first

- name: First setup of new server
  hosts: all
#  hosts: '{{ target }}'
  gather_facts: no
  remote_user: root
  port: 22
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: "{{ root_acct.sshkeypath }}"
  roles:
    - first


# Rather than set a hosts: all and limit, instead substitute a
# specific host address via the target variable and --extra-vars:
# ansible-playbook first.yml --extra-vars "target=imac-2.local"
