---
# Run as the deploy user but become root via sudo when needed.
- hosts: all
  user: "{{ deploy_acct.name }}"
  become: True
  gather_facts: True
  # force notified handlers to run even if there is was an error
  # somewhere.  Avoids leaving the machine in a screwball state.
  force_handlers: True      
  roles:
    - { role: common, tags: common }
    - { role: apache, tags: apache }
    - { role: mail, tags: mail }
    - { role: bacula-client, tags: bacula-client }


##- monitoring  # Monitoring role should be last. See roles/monitoring/README.md
