---    
# Debian 10 versions
# encfs         1.9.5-1+b1

## ENCFS is deprecated so consider switching to per directory ext4
## encryption with fscrypt.  Need to investigate how to best do this
## though.  https://tlbdk.github.io/ubuntu/2018/10/22/fscrypt.html

- name: EncFS present
  package: name=encfs state=present

- name: encrypted and cleartext directories present
  file: state=directory path={{item}}
  with_items:
    - "{{mail_spool_crypt}}"
    - "{{mail_spool_dir}}"
    - "{{mail_db_crypt}}"
    - "{{mail_db_dir}}"

    
##
## Mail Spool Directory
##
# Check for the presence of files in the crypt directory to see if the
# filesystem has been initialized yet.  The find just looks at the top
# level and does not recurse. On first call, EncFS gathers info and
# inits the filesystem.  The "p" is for paranoia mode.
# 
- name: encrypted mail spool is initialized
  find: paths={{mail_spool_crypt}} hidden=yes file_type=any
  register: encfs_spool_check
  changed_when: encfs_spool_check.matched == 0
  
- name: encrypted mail spool is mounted
  command: "/bin/mountpoint -q {{mail_spool_dir}}"
  register: encfs_spool_mount
  changed_when: encfs_spool_mount.rc != 0
  failed_when: false

- name: encrypted mail spool empty, creating new
  shell: printf "p\n{{ mail_spool_pw }}" | encfs {{mail_spool_crypt}} {{mail_spool_dir}} --public --stdinpass
  when: encfs_spool_check.matched == 0

- name: encrypted mail spool present, mounting existing
  shell: printf '{{ mail_spool_pw }}' | encfs {{mail_spool_crypt}} {{mail_spool_dir}} --public --stdinpass
  when: encfs_spool_check.matched > 0  and encfs_spool_mount.rc != 0

- name: encrypted mail spool, verified as mounted
  command: "/bin/mountpoint -q {{mail_spool_dir}}"
  changed_when: false

##
## Mail User Database Directory
##
# this just looks at the top level and does not recurse
- name: encrypted mail database is initialized
  find: paths={{mail_db_crypt}} hidden=yes file_type=any
  register: encfs_db_check
  changed_when: encfs_db_check.matched == 0

- name: encrypted mail database is mounted
  command: "/bin/mountpoint -q {{mail_db_dir}}"
  register: encfs_db_mount
  changed_when: encfs_db_mount.rc != 0
  failed_when: false

- name: encrypted mail database empty, creating new
  shell: printf "p\n{{ mail_spool_pw }}" | encfs {{mail_db_crypt}} {{mail_db_dir}} --public --stdinpass
  when: encfs_db_check.matched == 0

- name: encrypted mail database present, mounting existing
  shell: printf '{{ mail_spool_pw }}' | encfs {{mail_db_crypt}} {{mail_db_dir}} --public --stdinpass
  when: encfs_db_check.matched > 0  and encfs_db_mount.rc != 0

- name: encrypted mail database, verified as mounted
  command: "/bin/mountpoint -q {{mail_db_dir}}"
  changed_when: false


##
## VMAIL user/group and permissions
##
- name: group vmail present
  group: name=vmail state=present gid=5000

- name: user vmail present
  user: name=vmail group=vmail state=present uid=5000
    home={{mail_spool_dir}} shell=/usr/sbin/nologin

# use mode=02775 to setgid
- name: cleartext mail spool directory permissions 
  file: state=directory path={{mail_spool_dir}} group=vmail mode=0775

- name: cleartext mail database directory permissions
  file: state=directory path={{mail_db_dir}} mode=0755
  

