---
# Mail server components
- import_tasks: encfs.yml
- import_tasks: postfix.yml
- import_tasks: dovecot.yml
- import_tasks: rspamd.yml
  tags: rspamd

# For quick reimaging, grab local system data (keys, db).  Afterwards,
# you can use bacula to restore the user data (mail spool).  The when
# rule is needed to restrict to only these explicit tags, otherwise it
# fires on any inherited tags (like 'mail') too.
#
# Unfortunately, the combo of tag/never+when always prints skipped,
# unlike tag/never which is silent unless it fires.  We load this
# dynamically so it just prints skipped for the include_tasks action
# rather than skipped for each task within an import_tasks.
- name: create snapshot of system data
  include_tasks: snapshot.yml
  when: ansible_run_tags | intersect(['snapshot', 'mail-snapshot']) | length
  tags: [never, snapshot, mail-snapshot]

# - import_tasks: z-push.yml
# - import_tasks: autoconfig.yml
