---
# Debian 10 version
# rspamd        1.9.4   is in backports and good
# rspamd        1.8.1   is in stable and NOT recommended
# redis         5:5.0.3

# DEBIAN SPECIFIC - Need to call apt directly because we need the
# backports version of rspamd. The version in the stable repo is
# wicked old and rspamd.com is emphatic to not use it.  If you are
# using a different distro, adjust as needed.
#
- name: backports repository is configured as a source
  lineinfile:
    dest: /etc/apt/sources.list.d/{{item}}-backports.list
    line: "deb http://deb.debian.org/debian {{item}}-backports main"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ansible_distribution_release}}"
  register: backportconfig

- name: backports cache updated
  apt: update_cache=yes
  when: backportconfig is changed


- name: rspamd present from {{ansible_distribution_release}}-backports
  apt:
    name: rspamd
    state: present
    default_release: "{{ansible_distribution_release}}-backports"
    update_cache: yes
  tags: install-rspamd

  
- name: rspamd related packages present
  package:
    state: present
    name:
      - redis-server

- name: redis configuration 
  template: src={{ item }}.j2 dest=/etc/redis/{{ item }}
    owner=redis group=redis mode=640
  with_items:
    - redis.conf
  notify: restart redis

# local.d is merged, override.d overrides
- name: rspamd local configuration
  template: src=rspamd/local-{{ item }}.j2 dest=/etc/rspamd/local.d/{{ item }}
    owner=redis group=redis mode=640
  with_items:
    - options.inc
    - worker-proxy.inc
    - milter_headers.conf
  notify: restart rspamd

  
# Turn it on if we set the DKIM selector

# Restore snapshot from existing machine if needed
- name: Check for local dkim key backup
  become: False
  local_action:
    stat path="{{snapshot_dir}}/dkim_keys.tgz"
  register: dkim_key_backup

- name: restore local dkim key backup to {{dkim_keyroot|dirname}}
  unarchive:
    src: "{{snapshot_dir}}/dkim_keys.tgz"
    dest: "{{dkim_keyroot|dirname}}"
    owner: root
    group: root
  when: dkim_key_backup.stat.exists == true

- name: dkim key directory present
  file: path={{dkim_keyroot}} state=directory
        owner=_rspamd group=_rspamd mode=0755

- name: Generate DKIM keys
  shell: rspamadm dkim_keygen -b 2048 -s {{dkim_selector}} -d {{item}} -k {{item}}.{{dkim_selector}}.key > {{item}}.{{dkim_selector}}.txt
  args:
    creates: "{{dkim_keyroot}}/{{item}}.{{dkim_selector}}.key"
    chdir: "{{dkim_keyroot}}"
  with_items: "{{ mail_domains }}"
  notify: restart rspamd

- name: rspamd dkim signing local configuration
  template: src=rspamd/local-{{ item }}.j2 dest=/etc/rspamd/local.d/{{ item }}
    owner=redis group=redis mode=640
  with_items:
    - dkim_signing.conf
    - logging.inc
  notify: restart rspamd





  
- name: services enabled
  service: name={{ item }} state=started enabled=yes
  with_items:
    - redis-server
    - rspamd


# - name: Copy DMARC configuration into place
#   template: src=etc_rspamd_local.d_dmarc.conf.j2 dest=/etc/rspamd/local.d/dmarc.conf owner=root group=root mode="0644"
#   notify: restart rspamd

