---
# All defaults are found in bacula-common, so they can be used by both
# bacula-client and bacula-director.

# List of clients this director should use.  Mostly this is just the
# cloud group, but we may add some PCs later.  If we ever have more
# than one director, they will probably have different clients.
#
bacula_clients: "{{ (groups['cloud'] + groups['backup-server']) | unique}}"

# Select database backend: mysql, pgsql or sqlite3.  Mysql and
# Postgress need a password but Sqlite does not.
#bacula_db: sqlite3
#bacula_db: mysql
bacula_db: pgsql
bacula_db_pw: changeme

bacula_db_pkg:
  mysql: bacula-director-mysql
  pgsql: bacula-director-pgsql
  sqlite3: bacula-director-sqlite3

# ok for sqlite, research the settings for mysql/postgres
bacula_db_dump_args: bacula
