---
# An hour is good enough for packages where we want the latest 
pkg_cache_life: 3600

# Things that are common across all administered machines.  Initially
# we are only doing a single machine that provides web and mail for a
# variety of domains, but if we decide to move some domains onto their
# own machines, these settings would remain common to them.
# 
# Host specific things would go to host_vars/davecloud.net.yml
#
domain: davecloud.net
    
# Common credentials for root and deploy accounts.  Create crypted
# passwords with "mkpasswd --method=sha-512"
#
# This file defines all of the variables, including "vault_" stubs for
# sensitive ones like passwords.  The vault.yml file is encrypted and
# defines the sensitive values.  Use "ansible-vault edit vault.yml" to
# look at it.   
#
# The various things that can be called by lookup things can be found
# in /usr/lib/python2.7/dist-packages/ansible/plugins/lookup/
#
root_acct:
  name: root 
  sshkey: "{{ vault_root_sshkey }}"

deploy_acct:
  name: deploy
  group: users
  sshkey: "{{ vault_deploy_sshkey }}"
  passwd: "{{ vault_deploy_passwd }}"

main_user_shell: "/bin/bash"
  
# Admin email
# apticron, fail2ban reports will be sent to this address
admin_email: "admin@{{ domain }}"

# timezone, 'Etc/UTC' is another choice
timezone: 'US/Eastern'

#========================================
# Network and Firewall settings
#
#openports_list: [ 22, 80, 443 ]
openports_list: [ 22 ]

webports_list: [80, 443]
mailports_list: [25, 465, 587, 993]


#    IMAP | Port 993 (Secure Transport   — SSL function enabled)
#    POP3 | Port 995 (Secure Transport   — SSL function enabled)
#    IMAP | Port 143 (Insecure Transport — No SSL function enabled)
#    POP3 | Port 110 (Insecure Transport — No SSL function enabled)

#    SMTP | Port 587 (Insecure Transport, but can be upgraded to a secure connection using STARTTLS)
#    SMTP | Port 465 (Secure Transport — SSL function enabled)
#    SMTP | Port 25 (Outdated and not recommended. username/password authentication MUST be enabled if using this port.)


# blocked if defined
#blacklist_ip_list:
friendly_networks:
  - ""

# ntp_servers:

#========================================
# Webserver Settings
#
# Values to populate the Apache host configuration files.  Dictionary
# contains name (ServerName required), aliases (list of ServerAlias
# values), admin (ServerAdmin, defaults to webmaster@{{main.name}})
# and root (DocumentRoot, defaults to /var/www/{{host}})
web_main:
  - name: "{{ domain }}"
    aliases: [ "www.{{ domain }}" ] 

web_vhosts:
  - name: machineplan.com
    aliases: [ 'www.machineplan.com' ] 

certbot_certs:
  - domains: "{{ [ web_main.0.name ] + web_main.0.aliases }}"
  - domains: "{{ [ web_vhosts.0.name ] + web_vhosts.0.aliases }}"

  
# Mail domains and users.  Set into the virtual.sqlite database for
# use with postfix, dovecot, and roundcube.

# On Debian, smtpd normally runs chrooted to /var/spool/postfix, so we
# need to put the database under there or else it will not be able to
# authenticate.  For security at rest, we encrypt the directory where
# the user database is located as well as the mail spool.
# 
# The mail scripts for config and boot are just under /etc/postfix for
# simplicity.
#
mail_server_hostname: "mail.{{ domain }}"
mail_server_autoconfig_hostname: "autoconfig.{{ domain }}"

mail_cfg_dir: /etc/postfix
mail_db_crypt:  /var/spool/postfix/etc/maildb_crypt
mail_db_clear:  /var/spool/postfix/etc/maildb_clear
mail_db_util: "{{ mail_cfg_dir }}/mailcfg"
mail_db: "{{ mail_db_clear }}/maildb.sqlite3"

# Encrypt mail data at rest with EncFS, and cleartext mountpoint
mail_spool_crypt: "/var/mail_crypt"
mail_spool_clear: "/var/mail_clear"
mail_spool_pw:    "{{vault_mail_spool_pw}}"

mail_domains:
  - "{{ domain }}"
  - machineplan.com

mail_users:
  - email: "{{ admin_email }}"
    pw: "{{vault_mbox_admin_pw}}"
  - email: "dave@{{ domain }}"
    pw: "{{vault_mbox_dave_pw}}"
  - email: "somebody@machineplan.com"
    pw: "{{vault_mbox_someone_pw}}"

mail_aliases:
  - { src: "root@{{ domain }}",         dst: "{{ admin_email }}" }
  - { src: "postmaster@{{ domain }}",   dst: "{{ admin_email }}" }
  - { src: "webmaster@{{ domain }}",    dst: "{{ admin_email }}" }
  - { src: "abuse@{{ domain }}",        dst: "{{ admin_email }}" }
  - { src: "root@machineplan.com",         dst: "{{ admin_email }}" }
  - { src: "postmaster@machineplan.com",   dst: "{{ admin_email }}" }
  - { src: "webmaster@machineplan.com",    dst: "{{ admin_email }}" }
  - { src: "abuse@machineplan.com",        dst: "{{ admin_email }}" }
  - { src: "cloud@machineplan.com",        dst: "{{ admin_email }}" }

