---
# We do everything via the deploy_acct, may also set ansible_become=true
#ansible_ssh_user:               "{{ deploy_acct.name }}"
#ansible_ssh_private_key_file:   "{{ deploy_acct.sshkeypath }}"

# An hour is good enough for packages where we want the latest 
pkg_cache_life: 3600

# Things that are common across all administered machines.  Initially
# we are only doing a single machine that provides web and mail for a
# variety of domains, but if we decide to move some domains onto their
# own machines, these settings would remain common to them.
# 
# Host specific things would go to host_vars/davecloud.net.yml
#
domain: davecloud.net
    
# Common credentials for root and deploy accounts.
#
# This file defines all of the variables, including "vault_" stubs for
# sensitive ones like passwords.  The vault.yml file is encrypted and
# defines the sensitive values.  Use "ansible-vault edit vault.yml" to
# look at it.   
#
# The various things that can be called by lookup things can be found
# in /usr/lib/python2.7/dist-packages/ansible/plugins/lookup/
#
root_acct:
  name: root 
  sshpub: "{{ vault_root_sshpub }}"

deploy_acct:
  name: deploy
  group: users
  sshpub: "{{ vault_deploy_sshpub }}"
  sshkeypath: "{{ vault_deploy_sshkeypath }}"
  passwd: "{{ vault_deploy_passwd }}"

main_user_shell: "/bin/bash"
  
# Admin email
# apticron, fail2ban reports will be sent to this address
admin_email: "admin@{{ domain }}"

# timezone, 'Etc/UTC' is another choice
timezone: 'US/Eastern'

#========================================
# Network and Firewall settings
#
#    IMAP | Port 993 (Secure Transport   — SSL function enabled)
#    POP3 | Port 995 (Secure Transport   — SSL function enabled)
#    IMAP | Port 143 (Insecure Transport — No SSL function enabled)
#    POP3 | Port 110 (Insecure Transport — No SSL function enabled)

#    SMTP | Port 587 (Insecure Transport, but can be upgraded to a secure connection using STARTTLS)
#    SMTP | Port 465 (Secure Transport — SSL function enabled)
#    SMTP | Port 25 (Outdated and not recommended. username/password authentication MUST be enabled if using this port.)

#openports_list: "{{ sshports + webports + mailports + dnsports }}"
openports_list: "{{ sshports + webports + mailports }}"

#openports_udp_list: "{{ dnsports }}"

sshports: [22]
webports: [80, 443]
mailports: [25, 465, 587, 993]
dnsports: [53]


# blocked if defined
#blacklist_ip_list:
friendly_networks:
  - ""

# ntp_servers:

#========================================
# Snapshot/Backup Settings
#
# If present, the roles will restore tar files of data found in the
# directory below.  This can be populated by running the snapshot.yml
# playbook on the original machine and is useful if we are restoring
# or updating rather than a clean install.
#
snapshot_dir: "{{inventory_dir}}/snapshot/{{inventory_hostname}}"

# Known snapshots are:
# letsencrypt_backup.tgz - /etc/letsencrypt contents with symlinks


#========================================
# Webserver Settings
#
# Values to populate the Apache host configuration files.  Dictionary
# contains name (ServerName required), aliases (list of ServerAlias
# values), admin (ServerAdmin, defaults to webmaster@{{main.name}})
# and root (DocumentRoot, defaults to /var/www/{{host}})
web_vhosts:
  - name: "{{ domain }}"
    aliases:
      - www.{{ domain }}
      - mail.{{ domain }}
  - name: machineplan.com
    aliases:
      - www.machineplan.com


# Mail domains and users.  Set into the virtual.sqlite database for
# use with postfix, dovecot, and roundcube.

# On Debian, smtpd normally runs chrooted to /var/spool/postfix, so we
# need to put the database under there or else it will not be able to
# authenticate.  For security at rest, we encrypt the directory where
# the user database is located as well as the mail spool.
# 
# The mail scripts for config and boot are just under /etc/postfix for
# simplicity.
#
mail_server_hostname: "mail.{{ domain }}"
mail_server_autoconfig_hostname: "autoconfig.{{ domain }}"

mail_cfg_dir: /etc/postfix
mail_db_crypt:  /var/spool/postfix/etc/maildb_crypt
mail_db_clear:  /var/spool/postfix/etc/maildb
mail_db_util: "{{ mail_cfg_dir }}/mailcfg"
mail_db_name: maildb.sqlite3
mail_db: "{{ mail_db_clear }}/{{ mail_db_name }}"

# Encrypt mail data at rest with EncFS, and cleartext mountpoint
mail_spool_crypt: "/var/vmail_crypt"
mail_spool_clear: "/var/vmail"
mail_spool_pw:    "{{vault_mail_spool_pw}}"

mail_domains:
  - "{{ domain }}"
  - machineplan.com

mail_users:
  - email: "{{ admin_email }}"
    pw: "{{vault_mbox_admin_pw}}"
  - email: "dave@{{ domain }}"
    pw: "{{vault_mbox_dave_pw}}"
  - email: "somebody@machineplan.com"
    pw: "{{vault_mbox_someone_pw}}"

mail_aliases:
  - { src: "root@{{ domain }}",         dst: "{{ admin_email }}" }
  - { src: "postmaster@{{ domain }}",   dst: "{{ admin_email }}" }
  - { src: "webmaster@{{ domain }}",    dst: "{{ admin_email }}" }
  - { src: "security@{{ domain }}",     dst: "{{ admin_email }}" }
  - { src: "abuse@{{ domain }}",        dst: "{{ admin_email }}" }
  - { src: "root@machineplan.com",         dst: "{{ admin_email }}" }
  - { src: "postmaster@machineplan.com",   dst: "{{ admin_email }}" }
  - { src: "webmaster@machineplan.com",    dst: "{{ admin_email }}" }
  - { src: "security@machineplan.com",        dst: "{{ admin_email }}" }
  - { src: "abuse@machineplan.com",        dst: "{{ admin_email }}" }



# Encrypt private data at rest with EncFS, and cleartext mountpoint
private_dir_crypt:  /var/private_crypt
private_dir_clear:  /var/private
private_dir_pw:    "{{vault_mail_spool_pw}}"


# Bacula
bacula_client_director_pw: "{{ vault_bacula_client_pw }}"
bacula_storage_director_pw: "{{ vault_bacula_storage_pw }}"
bacula_console_director_pw: "{{ vault_bacula_console_pw }}"
bacula_tunnel_acct_sshkey: "{{ vault_bacula_sshpub }}"

  
dns_ns:  
  master: "ns1.{{ domain }}"
  email: "root.{{ domain }}"
  replica:
#  - { name: "ns1.foo.com", ip: "1.2.3.4" }

# name: "linode-slaves-v6"
#     provide-xfr: 2600:3c00::a NOKEY
#     provide-xfr: 2600:3c01::a NOKEY
#     provide-xfr: 2600:3c02::a NOKEY
#     provide-xfr: 2600:3c03::a NOKEY
#     provide-xfr: 2a01:7e00::a NOKEY
 
# pattern:
#     name: "linode-slaves-v4"
#     provide-xfr: 65.19.178.10 NOKEY
#     provide-xfr: 69.93.127.10 NOKEY
#     provide-xfr: 75.127.96.10 NOKEY
#     provide-xfr: 109.74.194.10 NOKEY
#     provide-xfr: 207.192.70.10 NOKEY

dns_mx:  
  master: "mail.{{ domain }}"
  backup:

dns_zones:  
  - name: "{{ domain }}"
    master: true
    cnames: [ www ]

  - name: machineplan.com
    cnames: [ www ]
  
