---
# Defines handlers applicable across all machines in the infrastructure.

- name: restart bacula director
  service: name=bacula-dir state=restarted

- name: restart bacula storage daemon
  service: name=bacula-sd state=restarted
