---
# Networks with relaxed checking, ignored by fail2ban, allowed to
# relay mail, etc
friendly_networks: []

# EncFS - mail spool
mail_spool_crypt: /var/vmail_crypt
mail_spool_clear: /var/vmail

# EncFS - mail database
mail_db_crypt:  /var/spool/postfix/etc/maildb_crypt
mail_db_clear:  /var/spool/postfix/etc/maildb

# EncFS - private dir for configs
private_dir_crypt:  /var/private_crypt
private_dir_clear:  /var/private

# Redis - used by rspamd.  By default, redis now binds only to
# localhost.   
redis_maxmen: 500mb
# default policy is noeviction, rspamd docs warn against evicting
# volatile data.  Not setting at the moment.
# redis_maxmen_policy: 

# Rspamd - spam filter

# Will do DKIM signing if the selector is set.  Usually follow a year
# month pattern (202001) so that we have a predictable pattern when we
# rotate them.  When near rotation time, we can set the selector_next
# var to pre-generate the keys, but do not use them.  This gives us a
# chance to get the public keys into DNS and let them propogate.
dkim_keyroot: "/var/vmail/dkim"
dkim_selector:
dkim_selector_next:

# utility variables to simplify the templates
dkim_selector_is_set: "{{ 
  dkim_selector|default(none) is not none and 
  dkim_selector|string|length > 0 }}"

dkim_selector_next_is_set: "{{ 
  dkim_selector_next|default(none) is not none and 
  dkim_selector_next|string|length > 0 }}"


#========================================
# For quick reimaging, the 'snapshot' tag will copy locally unique
# system data (like keys and certs) to the following directory, where
# it will be restored if present as part of a normal run. Afterwards,
# you can use bacula to restore any user data, like the mail spool.
#
snapshot_dir: "{{playbook_dir}}/snapshot/{{inventory_hostname}}"
