---
# Networks with relaxed checking, ignored by fail2ban, allowed to
# relay mail, etc
friendly_networks: []

# EncFS - mail spool
mail_spool_crypt: /var/vmail_crypt
mail_spool_clear: /var/vmail

# EncFS - mail database
mail_db_crypt:  /var/spool/postfix/etc/maildb_crypt
mail_db_clear:  /var/spool/postfix/etc/maildb

# EncFS - private dir for configs
private_dir_crypt:  /var/private_crypt
private_dir_clear:  /var/private

