---
# Snapshot of certbot keys in /etc/letsencrypt

# Restore snapshot from existing machine if needed
- name: backup certbot keys
  archive:
    path: /etc/letsencrypt
    format: gz
    dest: /tmp/letsencrypt_keys.tgz
  tags: [never, snapshot, web-snapshot]

- name: return certbot keys to mothership
  fetch:
    src: /tmp/letsencrypt_keys.tgz
    dest: "{{ snapshot_dir }}/"
    flat: yes
  tags: [never, snapshot, web-snapshot]

- name: clean up temporary archive
  file:
    path: /tmp/letsencrypt_keys.tgz
    state: absent
  tags: [never, snapshot, web-snapshot]
