---
#==============================
# DEFAULTS NEEDED BY MANY ROLES
#
# Directories and such for web data.  Should not depend on the choice
# of server (apache/nginx/etc).  May be used by other roles (mail,
# backup, etc) so broken out into this separate defaults-only role.
#
webdata_root: /var/www

# Values to populate host configuration.  The dictionary can contain
# the following values
# - name: "ServerName"  (required)
#   aliases: [list of ServerAlias]  (optional, usually www.{{name}})
#   admin: "admin email"    (defaults to webmaster@{{name}})
#   root: "document root"   (defaults to {{webdata_root}}/{{name}})
#   cert: "cert file"       (defaults to letsencrypt {{name}}/cert.pem)
#   certkey: "key file"     (defaults to letsencrypt {{name}}/privkey.pem)
#   certchain: "chain file" (defaults to letsencrypt {{name}}/chain.pem)
#

web_vhosts:
  - name: "{{ domain }}"
    aliases: [ "www.{{ domain }}" ] 


# start services at boot unless using encrypted dirs
web_services_bootstart: yes
