---
#==============================
# DEFAULTS NEEDED BY MANY ROLES
#
# Directories and such for web data.  Should not depend on the choice
# of server (apache/nginx/etc).  May be used by other roles (mail,
# backup, etc) so broken out into this separate defaults-only role.
#
webdata_root: /var/www
