---
# Dovecot for local mail delivery and IMAP access.  Do not install the
# dovecot-pop3 package, because we will only use IMAP.

- name: Dovecot and related packages present
  apt:
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-sqlite
    state: present

- name: Group vmail present
  group: name=vmail state=present gid=5000

- name: User vmail present
  user: name=vmail group=vmail state=present uid=5000
    home={{mail_spool_clear}} shell=/usr/sbin/nologin

- name: Spool directories for mail domain are present
  file: state=directory path="{{mail_spool_clear}}/{{ item }}"
    owner=vmail group=dovecot mode=0770
  with_items: "{{ mail_domains }}"

# - name: Spool directories for users are present
#   file: state=directory path="{{mail_spool_clear}}/{{ item.domain }}/{{ item.user }}/"
#   with_items: '{{ mail_users }}'

- name: Dovecot etc files present
  template: src="dovecot/{{item}}" dest="/etc/dovecot/{{item}}"
    owner=root group=root mode=0644
  with_items:
    - dovecot.conf
    - dovecot-sql.conf.ext
  notify: restart dovecot


#  Commented out mail_plugins sieve in 15-lda.conf.  Enable at a later
#  date.
- name: Dovecot conf.d files present
  template: src="dovecot/{{item}}.j2" dest="/etc/dovecot/{{item}}"
    owner=root group=root mode=0644
  copy: src=etc_dovecot_conf.d_{{ item }} dest=/etc/dovecot/conf.d/{{ item }}
  with_items:
    - 10-auth.conf
    - 10-ssl.conf
    - 15-lda.conf
    - auth-sql.conf.ext
  notify: restart dovecot

# 10-director.conf
# 10-logging.conf
# 10-mail.conf
# 10-master.conf
# 10-tcpwrapper.conf
# 15-mailboxes.conf
# 90-acl.conf
# 90-antispam.conf
# 90-plugin.conf
# 90-quota.conf
# 90-sieve.conf

# - name: Create before.d sieve scripts directory
#   file: path=/etc/dovecot/sieve/before.d state=directory owner=vmail group=dovecot recurse=yes mode=0770
#   notify: restart dovecot

# - name: Configure sieve script moving spam into Junk folder
#   copy: src=etc_dovecot_sieve_before.d_no-spam.sieve dest=/etc/dovecot/sieve/before.d/no-spam.sieve owner=vmail group=dovecot
#   notify: restart dovecot
  
- name: Template 20-imap.conf
  template: src=etc_dovecot_conf.d_20-imap.conf.j2 dest=/etc/dovecot/conf.d/20-imap.conf
  notify: restart dovecot

- name: Ensure correct permissions on Dovecot config directory
  file: state=directory path=/etc/dovecot
          group=dovecot owner=vmail mode=0770 recurse=yes
  notify: restart dovecot

- name: Set firewall rules for dovecot
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - imaps
    - pop3s
  tags: ufw

- name: Update post-certificate-renewal task
  copy:
    content: "#!/bin/bash\n\nservice dovecot restart\n"
    dest: /etc/letsencrypt/postrenew/dovecot.sh
    mode: 0755
    owner: root
    group: root
    

