---
# Dovecot for local mail delivery and IMAP access.  Do not install the
# dovecot-pop3 package, because we will only use IMAP.

- name: Dovecot and related packages present
  apt:
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-sqlite
    state: present

- name: Spool directories for mail domain are present
  file: state=directory path="{{mail_spool_clear}}/{{ item }}"
    owner=vmail group=vmail mode=0770
  with_items: "{{ mail_domains }}"

# - name: Spool directories for users are present
#   file: state=directory path="{{mail_spool_clear}}/{{ item.domain }}/{{ item.user }}/"
#   with_items: '{{ mail_users }}'


- name: Dovecot etc files present
  template: src="dovecot/{{item}}" dest="/etc/dovecot/{{item}}"
    owner=root group=root mode=0644
  with_items:
    - dovecot.conf
    - dovecot-sql.conf.ext
  notify: restart dovecot


#  Commented out mail_plugins sieve in 15-lda.conf.  Enable at a later
#  date.  Soverign also has a 20-imap.conf that loads some plugins and
#  also has a protocol lmtp.   Not sure whether it is needed.

- name: Dovecot conf.d files present
  template: src="dovecot/{{item}}" dest="/etc/dovecot/conf.d/{{item}}"
    owner=root group=root mode=0644
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf
    - 10-ssl.conf
    - 15-lda.conf
    - 15-mailboxes.conf
    - auth-sql.conf.ext
  notify: restart dovecot

# 90-antispam.conf
# 90-sieve.conf

# - name: Create before.d sieve scripts directory
#   file: path=/etc/dovecot/sieve/before.d state=directory owner=vmail group=dovecot recurse=yes mode=0770
#   notify: restart dovecot

# - name: Configure sieve script moving spam into Junk folder
#   copy: src=etc_dovecot_sieve_before.d_no-spam.sieve dest=/etc/dovecot/sieve/before.d/no-spam.sieve owner=vmail group=dovecot
#   notify: restart dovecot

# No need, we don't have any special database passwords in the configs
# - name: Ensure correct permissions on Dovecot config directory
#   file: state=directory path=/etc/dovecot
#           group=dovecot owner=vmail mode=0770 recurse=yes
#   notify: restart dovecot


- name: certbot post-renew hook to reload dovecot
  copy:
    content: "#!/bin/bash\n\nservice dovecot reload\n"
    dest: /etc/letsencrypt/renewal-hooks/post/dovecot
    owner: root
    group: root
    mode: 0755
    

