---
- name: bacula client packages are installed
  apt:
    name:
      - bacula-client
    state: present

- name: bacula password has real value
  fail: msg="Set bacula_client_director_pw to a real value"
  when: bacula_client_director_pw == "changeme"
    
- name: bacula client config file
  template:
    src: bacula-fd.conf.j2
    dest: /etc/bacula/bacula-fd.conf
  notify:
    - restart bacula client

- name: bacula working directory present
  file: state=directory path="{{ bacula_client_filedaemon_workdir }}"
    owner=root group=bacula mode=0770

## Since the client is in the cloud and our director will likely be
## NATed and behind a firewall, we leave the Bacula ports blocked on
## the client and have the director set up an ssh tunnel.  Set up a
## restricted backup account with a separate key just to set up the
## tunnel to port 9102.
## 


    
# RedHat and Suse would also need stuff in sysconfig

- name: bacula client service enabled
  service: name=bacula-fd enabled=yes

- name: bacula client service started
  service: name=bacula-fd state=started
    
