---
# Set up emacs and vim.  Install the No X variants because we are just
# doing a server machine.  Also include some other emacs modes that we
# may want.
- name: text editors (emacs/vim) installed
  package:
    state: present
    name:
      - emacs-nox
      - emacs-goodies-el
      - yaml-mode
      - vim-nox

- name: default .emacs file installed for all users
  copy:
    src: dotemacs
    dest: "{{ item.dst }}/.emacs"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items:
    - { dst: '/root', owner: 'root', group: 'root' }
    - { dst: '/etc/skel', owner: 'root', group: 'root' }
    - { dst: "/home/{{ deploy_acct }}", owner: "{{ deploy_acct }}", group: "{{ deploy_acct_group }}" }
