---
- name: latest network filtering packages are installed 
  apt:
    name:
      - iptables-persistent
      - fail2ban
    state: latest
      
- name: iptables v4 configured
  template:
    src: etc/iptables/{{ item }}.j2
    dest: /etc/iptables/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - testrules.v4
  register: iptablesconf4
  when: ansible_default_ipv4.interface is defined

- name: iptables v6 configured
  template:
    src: etc/iptables/{{ item }}.j2
    dest: /etc/iptables/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - testrules.v6
  register: iptablesconf6
  when: ansible_default_ipv6.interface is defined

- name: iptables v4 configs loaded and persistent
  shell: iptables-restore /etc/iptables/testrules.v4 && iptables-save > /etc/iptables/rules.v4
  when: iptablesconf4.changed
  notify:
    - restart netfilter-persistent
    - restart fail2ban

- name: iptables v6 configs loaded and persistent
  shell: ip6tables-restore /etc/iptables/testrules.v6 && ip6tables-save > /etc/iptables/rules.v6
  when: iptablesconf6.changed
  notify:
    - restart netfilter-persistent
    - restart fail2ban

- name: iptables services are started and enabled
  service: name=netfilter-persistent state=started enabled=yes
  when: iptablesconf4.changed or iptablesconf6.changed

  
- name: fail2ban jails configured
  template:
    src: etc/fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban


# On Debian 9, the default install of fail2ban is 0.9.x, but the ssh
# configs there are a bit outdated.  Use the most recent configs from
# the 0.9 branch at https://github.com/fail2ban/fail2ban.  We will be
# using the sshd-aggressive jail because it picks up "Did not receive
# identification string" and "Unable to negotiate with" failures that
# the default did not.
#
# Revisit this when updating to fail2ban 0.10, 0.11, or later as the
# filter format changes a bit.
#
- name: fail2ban extra filters installed
  copy:
    src: etc/fail2ban/filter.d/{{ item }}
    dest: /etc/fail2ban/filter.d
    owner: root
    group: root
    mode: 0644
  with_items:
    - sshd-extra.conf
  notify: restart fail2ban

- name: fail2ban is started
  service: name=fail2ban state=started

