---
- name: network filtering packages are installed 
  package:
    state: present
    name:
      - iptables-persistent
      - fail2ban

- debug:
    msg:
      - OPEN TCP PORTS {{ firewall_ports_tcp }}
      - OPEN UDP PORTS {{ firewall_ports_udp }}
      
# iproute2 has the new ss command
# net-tools has the legacy commands including netstat
      
- name: iptables v4 configured
  template:
    src: testrules.v4.j2
    dest: /etc/iptables/testrules.v4
    owner: root
    group: root
    mode: 0644
  register: iptablesconf4
  when: ansible_default_ipv4.interface is defined

- name: iptables v6 configured
  template:
    src: testrules.v6.j2
    dest: /etc/iptables/testrules.v6
    owner: root
    group: root
    mode: 0644
  register: iptablesconf6
  when: ansible_default_ipv6.interface is defined

- name: iptables v4 configs loaded and persistent
  shell: iptables-restore /etc/iptables/testrules.v4 && iptables-save > /etc/iptables/rules.v4
  when: iptablesconf4.changed
  notify:
    - restart netfilter-persistent
    - restart fail2ban

- name: iptables v6 configs loaded and persistent
  shell: ip6tables-restore /etc/iptables/testrules.v6 && ip6tables-save > /etc/iptables/rules.v6
  when: iptablesconf6.changed
  notify:
    - restart netfilter-persistent
    - restart fail2ban

- name: iptables services are started and enabled
  service: name=netfilter-persistent state=started enabled=yes
  when: iptablesconf4.changed or iptablesconf6.changed

# Assume we will have ssh, apache, postfix, and dovecot and enable the
# jails for them.  If we do not use some of those, perhaps we can play
# some tag and template games to selectively enable parts.
# 
- name: fail2ban jails configured
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: fail2ban is started
  service: name=fail2ban state=started

