---
- { import_tasks: hostname.yml,         tags: hostname }
- { import_tasks: locale.yml,           tags: locale }
- { import_tasks: firewall.yml,         tags: firewall }
- { import_tasks: ntp.yml,              tags: ntp }
- { import_tasks: upgrades.yml,         tags: unattended-upgrades }
- { import_tasks: logrotate.yml,        tags: logrotate }
- { import_tasks: editor.yml,           tags: editor }

# Only install logwatch if we specifically request it for a machine
- { include_tasks: logwatch.yml,        when: use_logwatch }

# Can add alias to root .bashrc
# alias fail2ban-all="fail2ban-client status | sed -n 's/,//g;s/.*Jail list://p' | xargs -n1 fail2ban-client status"

# Add bash completion too.
#  if [ -f /usr/share/bash-completion/bash_completion ]; then
#    . /usr/share/bash-completion/bash_completion
#  elif [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
