---
# - name: apt package cache up-to-date
#   apt:
#     update_cache: yes
#     cache_valid_time: "{{ pkg_cache_life }}"

- { import_tasks: hostname.yml,         tags: hostname }
- { import_tasks: locale.yml,           tags: locale }
- { import_tasks: firewall.yml,         tags: firewall }
- import_tasks: ntp.yml
- import_tasks: upgrades.yml
- import_tasks: editor.yml

# test but probably not what we want
# - import_tasks: debsums.yml

# - import_tasks: disk-check.yml
# - import_tasks: htop.yml
# - import_tasks: needrestart.yml
# - import_tasks: dnsmasq.yml
