---
- name: timezone set to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: ntp packages are installed
  apt: name=ntp state=present

- name: ntp configured
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ntp

- name: ntp is started and enabled
  service: name=ntp state=started enabled=yes

