---
#========================================
# Webserver Settings
#
# Values to populate the Apache host configuration files.  Dictionary
# contains name (ServerName required), aliases (list of ServerAlias
# values), admin (ServerAdmin, defaults to webmaster@{{main.name}})
# and root (DocumentRoot, defaults to /var/www/{{host}})
web_vhosts:
  - name: "{{ domain }}"
    aliases: [ "www.{{ domain }}" ] 

#========================================
# Certbot Settings
#

certbot_script: certbot
certbot_admin_email: "{{ admin_email }}"

certbot_test_util: /etc/letsencrypt/testcertnames
certbot_certs: []
# - email: janedoe@example.com
#   domains:
#     - example1.com
#     - example2.com
# - domains:
#     - example3.com
certbot_create_command: >-
  {{ certbot_script }} certonly --standalone --noninteractive --agree-tos
  --email {{ cert_item.email | default(certbot_admin_email) }}
  -d {{ cert_item.domains | join(',') }}

certbot_modify_command: >-
  {{ certbot_script }} certonly --standalone --noninteractive
  --cert-name {{ cert_item.domains | first | replace('*.', '') }}
  -d {{ cert_item.domains | join(',') }}


certbot_create_standalone_stop_services:
  - apache2

