---
#========================================
# Webserver Settings
#
# Values to populate the Apache host configuration files.  Dictionary
# contains name (ServerName required), aliases (list of ServerAlias
# values), admin (ServerAdmin, defaults to webmaster@{{main.name}})
# and root (DocumentRoot, defaults to /var/www/{{host}})

web_vhosts:
  - name: "{{ domain }}"
    aliases: [ "www.{{ domain }}" ] 

#========================================
# Certbot Settings
#

certbot_script: certbot
certbot_admin_email: "{{ admin_email }}"

certbot_test_util: /etc/letsencrypt/testcertnames

# Use jinja2 to build list of name+aliases for each host
# domains: "{{ [ web_vhosts.[i].name ] + web_vhosts.[i].aliases }}"
certbot_certs: >-
  {%- set ns = namespace(ids=[]) -%}
  {%- for i in web_vhosts -%}
  {{- ns.ids.append({ 'domains': [ i.name ] + i.aliases }) -}}
  {%- endfor -%}
  {{- ns.ids -}}
  
certbot_create_command: >-
  {{ certbot_script }} certonly --standalone --noninteractive --agree-tos
  --email {{ cert_item.email | default(certbot_admin_email) }}
  -d {{ cert_item.domains | join(',') }}

certbot_modify_command: >-
  {{ certbot_script }} certonly --standalone --noninteractive
  --cert-name {{ cert_item.domains | first | replace('*.', '') }}
  -d {{ cert_item.domains | join(',') }}


certbot_create_standalone_stop_services:
  - apache2

