---
#==============================
# DEFAULTS NEEDED BY MANY ROLES
#
# Directories and such used by other roles (backup, etc) so set by the
# separate web-dflts role.
#
#webdata_root:
#web_vhosts:

#==============================
# DEFAULTS NEEDED BY ONLY THIS ROLE
#

# always need the rewrite and ssl modules for our own use, can set the
# apache_modules vars to get extras.  Note - ssl is always there but
# throws error if we try to specify it
apache_default_modules: [ rewrite, ssl, headers ]
apache_modules: [ ]

# permanent redirect from http to https
apache_use_https: yes
apache_force_https: yes

# OCSP Stapling
# http://httpd.apache.org/docs/2.4/ssl/ssl_howto.html#ocspstapling
# Add mod_socache_shmcb to mod enabled.  The 32k shared memory cache
# that is used by default is good for a few certs, but each cert can
# require up to 10k cache so bump it up if you are running many
# vhosts.
apache_staple_sz: 32768
apache_staple_on: no


apache_host_dflt_root: "{{webdata_root}}/{{ host.name }}"
