---
#==============================
# DEFAULTS NEEDED BY MANY ROLES
#
# Directories and such used by other roles (backup, etc) so set by the
# separate mail-dflts role.
#
#mail_server_hostname:

#==============================
# DEFAULTS NEEDED BY ONLY THIS ROLE
#
# Relay all mail through a smarthost with authentication using the
# given account and password.
mail_cfg_dir: /etc/postfix

mail_relay_acct:   "relay@{{ domain }}"
mail_relay_pw:     "{{ vault_relay_pw }}"

mail_relay_host:   "{{ mail_server_hostname }}"
mail_relay_port:   587
#mail_relay_port:   465
