---
# Relay all mail through a smarthost with authentication using the
# given account and password.

mail_relay_acct:   "relay@{{ domain }}"
mail_relay_pw:     "{{ vault_relay_pw }}"

mail_relay_host:   "{{ mail_server_hostname }}"
mail_relay_port:   587
#mail_relay_port:   465
