---
bacula_client_host: "{{ inventory_hostname }}"

bacula_client_name: "{{ bacula_client_host }}-fd"
bacula_client_fdport: 9102
bacula_client_workdir: /var/spool/bacula
bacula_client_piddir: /var/run
bacula_client_max_jobs: 20

bacula_client_director_name: bacula-dir
bacula_client_director_pw: changeme

# This is symbolic name passed by the director to the client that
# needs to resolve to the storage machine.  Since we are working over
# a tunnel this must not resolve to anything real so we put an entry
# in /etc/hosts to map it to 127.0.0.1
bacula_tunnel_sd_addr: bacula-sd.local
bacula_tunnel_acct:
  name: bacula-tun
  group: users
  sshkey: "{{ vault_bacula_sshkey }}"
  passwd: '*'

