---

- name: Use delv to check the status of DNSSEC
  when: bind.dnssec.active
  tags: check
  shell: >-
    delv @127.0.0.1 -a /etc/bind/keys/live/authority.key
    +root={{ network.domain }} {{ network.domain }}. SOA +multiline
    | grep '^; fully validated'

- name: Check DNS keys
  when: bind.dnssec.active
  tags: check
  shell: >-
    dig @{{ external_ip }} {{ network.domain }}. DNSKEY +multiline +noall +answer
    | grep 'IN\sDNSKEY'

- name: Check DNS signatures
  when: bind.dnssec.active
  tags: check
  shell: >-
    dig @{{ external_ip }} {{ network.domain }}. SOA +dnssec +multiline
    | grep 'IN\sRRSIG'

- name: Send the keys to the postmaster, by email
  when: bind.dnssec.active
  tags: mail
  mail:
    from: 'root@{{ network.domain }}'
    subject: 'DNSSEC keys for {{ network.domain }}'
    to: 'postmaster@{{ network.domain }}'
    body: >-
      Find attached the public DNS keys for the domain {{ network.domain }}.
      There is two keys, one is Zone Signing Key, and the other is Key Signing Key.
      Follow the instructions of your DNS provider to publish them online.
    attach:
      - '/etc/bind/keys/live/zsk.key'
      - '/etc/bind/keys/live/ksk.key'
