---
# The bacula-server package brings in bacula-director, bacula-sd, and
# bacula-bscan
- name: bacula director installed
  package:
    state: present
    name:
      - bacula-server

- name: bacula storage password has real value
  fail: msg="Set bacula_storage_pw to a real value"
  when: bacula_storage_pw == "changeme"

- name: bacula console password has real value
  fail: msg="Set bacula_console_pw to a real value"
  when: bacula_console_pw == "changeme"
      
# install one database backend: mysql, pgsql or sqlite
# include: mysql.yml
# include: pgsql.yml
# include: sqlite.yml

# bacula-storage-mysql
# bacula-storage-postgresql
# Package bacula-tray-monitor


- name: bacula director config file
  template:
    src: bacula-dir.conf.j2
    dest: /etc/bacula/bacula-dir.conf
  notify:
    - restart bacula director

- name: cloud client configurations present
  template:
    src: client.conf.j2
    dest: /etc/bacula/{{hostvars[item].inventory_hostname_short}}-job.conf
  with_items: "{{ bacula_clients }}"
  notify:
    - restart bacula director

- name: bacula storage daemon config file
  template:
    src: bacula-sd.conf.j2
    dest: /etc/bacula/bacula-sd.conf
  notify:
    - restart bacula storage daemon

- name: bacula server working directories present
  file: state=directory path="{{ item }}"
    owner=root group=bacula mode=0770
  with_items:
    - "{{ bacula_director_workdir }}"
    - "{{ bacula_storage_workdir }}"
    - "{{ bacula_storage_datadir }}"

- name: local storage director resolves to loopback
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "127.0.0.1 {{ item }}"
    state: present
  with_items: 
    - "{{ bacula_storage_host }}"


## Console?
    
# RedHat and Suse would also need stuff in sysconfig

- name: bacula services enabled and running
  service: name={{item}} enabled=yes state=started
  with_items:
    - bacula-dir
    - bacula-sd
  
