---
# The bacula-server package brings in bacula-director, bacula-sd, and
# bacula-bscan
- name: bacula director installed
  package:
    state: present
    name:
      - bacula-server
      - bacula-console

- name: bacula storage password has real value
  fail: msg="Set bacula_storage_pw to a real value"
  when: bacula_storage_pw == "changeme"

- name: bacula console password has real value
  fail: msg="Set bacula_console_pw to a real value"
  when: bacula_console_pw == "changeme"
      
# install one database backend: mysql, pgsql or sqlite
# include: mysql.yml
# include: pgsql.yml
# include: sqlite.yml

# bacula-storage-mysql
# bacula-storage-postgresql
# Package bacula-tray-monitor

- name: bacula server working directories present
  file: state=directory path="{{ item }}"
    owner=root group=bacula mode=0770
  with_items:
    - "{{ bacula_director_workdir }}"
    - "{{ bacula_storage_workdir }}"
    - "{{ bacula_storage_datadir }}"
    - /etc/bacula/tunnel

# Configs for director, storage daemon, and console
- name: bacula config files present
  template: src={{item}}.j2
    dest=/etc/bacula/{{item}}
    owner=root group=bacula mode=0640
  with_items:
    - bacula-dir.conf
    - bacula-sd.conf
    - bconsole.conf
  notify:
    - restart bacula director
    - restart bacula storage daemon

- name: cloud client configurations present
  template:
    src: client.conf.j2
    dest: /etc/bacula/{{hostvars[item].inventory_hostname_short}}-job.conf
    owner: root
    group: bacula
    mode: 0640
  with_items: "{{ bacula_clients }}"
  notify:
    - restart bacula director

# SSH Tunnel Things ---------------------------------------
- name: bacula tunnel script present
  template: src={{item}} dest=/etc/bacula/{{item}}
    owner=root group=bacula mode=0750
  with_items:
    - ssh-tunnel.sh

- name: bacula tunnel keys for all clients
  copy: src={{item.src}}
    dest=/etc/bacula/tunnel/{{item.dst}}
    owner=root group=bacula mode=0640
  with_items: >-
    {%- set ns = namespace(keys=[]) -%}
    {%- for i in bacula_clients -%}
    {{- ns.keys.append( {
      "src": hostvars[i].bacula_tunnel_sshkeypath |
      default(bacula_default_tunnel_sshkeypath),
      "dst": hostvars[i].bacula_tunnel_sshkeyname |
      default(bacula_default_tunnel_sshkeyname) } ) -}}
    {%- endfor -%}
    {{- ns.keys | unique -}}

# Storage director is on the same machine, but we want to give it a
# distinct name for use when tunneling.
- name: local storage director resolves to loopback
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "127.0.0.1 {{ item }}"
    state: present
  with_items: 
    - "{{ bacula_storage_host }}"

# RedHat and Suse would also need stuff in sysconfig

- name: bacula services enabled and running
  service: name={{item}} enabled=yes state=started
  with_items:
    - bacula-dir
    - bacula-sd
  
