---
---
- name: bacula director packages are installed
  apt:
    name:
      - bacula-director
# okus one of       
#      - bacula-director-pgsql
#      - bacula-director-mysql
#      - bacula-director-sqlite3
    state: present
