---
- name: mysql packages installed
  package:
    name:
      - bacula-director-mysql
      - MySQL-python
      - mysql
    state: present

- name: Create MySQL DB
  mysql_db:
    name: "{{ bacula_director_config_catalog_options_db_name }}"
    login_host: "{{ bacula_director_config_catalog_options_db_address }}"
    login_port: "{{ bacula_director_config_catalog_options_db_port }}"
    login_user: "{{ bacula_director_db_login_user }}"
    login_password: "{{ bacula_director_db_login_password }}"
    config_file: "{{ bacula_director_db_mysql_config }}"
  register: bacula_director_db_mysql_created
  when: >
    bacula_director_db_engine == 'mysql'
  tags:
    - bacula_director_db

- name: Import Bacula DB schema for MySQL
  shell: >
    env sed -n '/END-OF-DATA/,/END-OF-DATA/{/END-OF-DATA/d;/db_name/d;p}' /usr/libexec/bacula/make_mysql_tables |
    mysql
    --user={{ bacula_director_db_login_user }}
    --password={{ bacula_director_db_login_password }}
    --host={{ bacula_director_config_catalog_options_db_address }}
    --port={{ bacula_director_config_catalog_options_db_port }}
    {{ bacula_director_config_catalog_options_db_name }}
  args:
    executable: /bin/bash
  when: >
    bacula_director_db_engine == 'mysql' and
    bacula_director_db_mysql_created.changed
  tags:
    - bacula_director_db

- name: Create MySQL user
  mysql_user:
    login_host: "{{ bacula_director_config_catalog_options_db_address }}"
    login_port: "{{ bacula_director_config_catalog_options_db_port }}"
    login_user: "{{ bacula_director_db_login_user }}"
    login_password: "{{ bacula_director_db_login_password }}"
    config_file: "{{ bacula_director_db_mysql_config }}"
    host: "{{ bacula_director_db_mysql_user_host }}"
    name: "{{ bacula_director_config_catalog_options_db_user }}"
    password: "{{ bacula_director_config_catalog_options_db_password }}"
    priv: "{{ bacula_director_db_user_priv }}"
  when: bacula_director_db_engine == 'mysql'
  tags:
    - bacula_director_db

