---
- name: postgresql packages installed
  package:
    name:
      - bacula-director-pgsql
      - python-psycopg2
      - postgresql
    state: present

# /usr/share/bacula-director/create_postgresql_database
# /usr/share/bacula-director/drop_postgresql_database
# /usr/share/bacula-director/drop_postgresql_tables
# /usr/share/bacula-director/grant_postgresql_privileges
# /usr/share/bacula-director/make_postgresql_tables
# /usr/share/bacula-director/update_postgresql_tables

- name: Create PostreSQL DB
  postgresql_db:
    name: "{{ bacula_director_config_catalog_options_db_name }}"
    login_host: "{{ bacula_director_config_catalog_options_db_address }}"
    port: "{{ bacula_director_config_catalog_options_db_port }}"
    login_user: "{{ bacula_director_db_login_user }}"
    login_password: "{{ bacula_director_db_login_password }}"
    encoding: SQL_ASCII
    lc_collate: C
    lc_ctype: C
    template: template0
  register: bacula_director_db_pgsql_created
  when: >
    bacula_director_db_engine == 'pgsql'
  tags:
    - bacula_director_db

- name: Import Bacula DB schema for PostgreSQL
  shell: >
    env sed -n '/END-OF-DATA/,/END-OF-DATA/{/END-OF-DATA/d;p}' /usr/libexec/bacula/make_postgresql_tables |
    psql
    --username {{ bacula_director_db_login_user }}
    --host {{ bacula_director_config_catalog_options_db_address }}
    --port {{ bacula_director_config_catalog_options_db_port }}
    --dbname {{ bacula_director_config_catalog_options_db_name }}
    --file -
  args:
    executable: /bin/bash
  environment:
    PGPASSWORD: "{{ bacula_director_db_login_password }}"
  when: >
    bacula_director_db_engine == 'pgsql' and
    bacula_director_db_pgsql_created.changed
  tags:
    - bacula_director_db

- name: Create PostgreSQL user
  postgresql_user:
    name: "{{ bacula_director_config_catalog_options_db_user }}"
    db: "{{ bacula_director_config_catalog_options_db_name }}"
    password: "{{ bacula_director_config_catalog_options_db_password }}"
    priv: "{{ bacula_director_db_user_priv }}"
    login_user: "{{ bacula_director_db_login_user }}"
    login_password: "{{ bacula_director_db_login_password }}"
    login_host: "{{ bacula_director_config_catalog_options_db_address }}"
    port: "{{ bacula_director_config_catalog_options_db_port }}"
  when: bacula_director_db_engine == 'pgsql'
  tags:
    - bacula_director_db
